apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: doubler-base


resources:
- service.yaml
- configMap.yaml
labels:
- includeSelectors: true
  pairs:
    app: doubler-go
